/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hodag' at '17/11/01 15:57' with Gradle 2.14.1
 *
 * @author hodag, @date 17/11/01 15:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
